### ISSUE TITLE
Blob.size is Int in v0.9.1 but Double in v0.9.2 -- WHY???

### ISSUE THREAD

**Issue by WellRedPandit** [scala-js/scala-js-dom#309]
```scala
def size: Double = js.native
```
https://github.com/scala-js/scala-js-dom/blob/v0.9.2/src/main/scala/org/scalajs/dom/raw/lib.scala#L7249

```scala
def size: Int = js.native
```
https://github.com/scala-js/scala-js-dom/blob/v0.9.1/src/main/scala/org/scalajs/dom/raw/lib.scala#L7091

The change does break existing code. How could it be considered a patch version???

P.S. Wouldn't Long have been a better choice?

**Comment by sjrd** [comment]
First, please calm down. Your tone ("WHY???", "How could it be considered a patch version???") is not appropriate for communicating about an issue.

It has become a `Double` because [the specification](https://w3c.github.io/FileAPI/#dfn-size) says that it is an `unsigned long long`, which in JavaScript translates to a `number` whose range exceeds 32 bits. Now, such a `number` in Scala.js is a `Double`. An `Int` is too small, and `Long`s are [opaque](https://stackoverflow.com/q/27821841/1829647).

Now why has the change happened in a "patch" version? (Actually, given we're in 0.x, it's actually more like a *minor* version.) Because, since it is a JS type, such a change is backward *binary* compatible, even if it is not *source* compatible. Binary incompatibilities require a major version bump, while source incompatibilities only require a minor version bump.

This is in line with [the recommended versioning scheme](http://docs.scala-lang.org/overviews/core/binary-compatibility-for-library-authors.html#versioning-scheme---communicating-compatibility-breakages)--OK, that's unsurprising, since I basically designed that versioning scheme, but still, it was approved by other prominent members of the Scala community. Read the full page for more rationale, or come listen to [my talk at Scala Sphere 2018](http://scala.sphere.it/sebastien-doeraene).

**Comment by WellRedPandit** [comment]
Source compatibility has been broken. I've had to refactor and rebuild my app. Therefore, in my view, the change was not a patch. No matter how your community spins semantic versioning.

> approved by other prominent members of the Scala community

Collective stupidity is no reason.

> given we're in 0.x

Li Haoyi [keeps harping on](http://www.lihaoyi.com/post/FromfirstprinciplesWhyIbetonScalajs.html) about scala.js being production-ready. Please do at liberty continue to fuck with his evangelism.
