### ISSUE TITLE
Synchronous XHR Extension

### ISSUE THREAD

**Issue by exoego** [scala-js/scala-js-dom#332]
I want to send XHR to server on window unload.
For such purpose, modern browsers added `sendBeacon` API which is experimentally available in [scala-js-dom](https://github.com/scala-js/scala-js-dom/blob/0eeaa48e1e05357c961b945ec277a2d77fb89e1e/src/main/scala/org/scalajs/dom/experimental/beacon/package.scala).

However, I need [fallback to synchronous XHR like this](https://stackoverflow.com/a/15479699/92396869) for legacy browsers that does not support `sendBeacon` API.

It would be helpful if [Ajax extension](https://github.com/scala-js/scala-js-dom/blob/0eeaa48e1e05357c961b945ec277a2d77fb89e1e/src/main/scala/org/scalajs/dom/ext/Extensions.scala) has `async` argument, so that one can use synchronous XHR if necessary.

```scala
def apply(method: String, url: String, data: InputData, timeout: Int, 
     headers: Map[String, String], withCredentials: Boolean, responseType: String,
     async: Boolean = true /* THIS*/ ): Future[dom.XMLHttpRequest] = {
     ...
    req.open(method, url, async /* THIS */)
```

**Comment by sjrd** [comment]
The methods in `Ajax` return `Future`s. It makes no sense to allow synchronous requests in these methods, because you wouldn't be able to access the result synchronously anyway. If you want synchronous AJAX requests, I suggest you build your own abstraction on top of `dom.XMLHttpRequest`. It is out of scope for the `Ajax` extension in this repo.
